version: "3.9"

services:
  flask:
    build:
      context: .
      dockerfile: ./docker/images/flask/Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - "./app:/var/www/app"
    depends_on:
      - mysql

  mysql:
    build: ./docker/images/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: {}
